let USERNAME_KEY;
USERNAME_KEY = 'leo';

let TICKETS_KEY;
TICKETS_KEY = 'TICKETS';

let LOGGED_IN_KEY;
LOGGED_IN_KEY = 'E_LOGADO';

let ITINERARY_KEY;
ITINERARY_KEY = 'ITINERARY';

let TRAVEL_KEY;
TRAVEL_KEY = 'TRAVELS';
